import { useEffect, useState, useRef } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import { getSessionFromContext } from '../../services/auth';
import { getProducts } from '../../services/product';
import { getAvatar } from '../../services/user';

import styles from '../../styles/Home.module.css'

import PageHeader from '../../components/header/header';
import PageFooter from '../../components/footer/footer';
import Products from '../../components/product/product-list';
import sampleData from '../../public/getProducts.json'

export async function getServerSideProps(context) {
  // const user = await getSessionFromContext(context);
  // if (!user) {
    // redirectTo(context, '/auth/signin');
  // }

  const products = await getProducts();
  /*.then(res => { 
      console.log(res.data);
      return res.data;
    });*/
    
  // console.log(products.data.data);

  const avatar = await getAvatar();
  console.log(avatar);

  return {
    props: {
      // user,
      products: products.data.data,
      // products: sampleData.dataList,
      avatar:avatar.data.avatar,
      cover:avatar.data.cover,
    }
  };
}

export default function Home(props) {

  const [products, setProducts] = useState(props.products);

  return (
    <div className={styles.container}>
      <Head>
        <title>Ngo xanh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageHeader avatar={props.avatar} cover={props.cover}/>
      <div className='top-product-container'>
        <div className='top-product-title'>Sản phẩm</div>
        <div className='top-product'>
          <Products
            products={products}
          />
        </div>
      </div>
      <div style={{minHeight:'10vh'}}></div>
      <footer className={styles.footer}>
        <PageFooter />
        <div style={{minHeight:'10vh'}}></div>
      </footer>
    </div>
  )
}
