import { useEffect, useState, useRef } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import { getSessionFromContext } from '../services/auth';
import Router from 'next/router';
import Select from 'react-select';

import { getProducts } from '../services/product';

import styles from '../styles/Home.module.css'

import TopProduct from '../components/top-product/top-product';
import PageFooter from '../components/footer/footer';
import sampleData from '../public/getProducts.json'

export async function getServerSideProps(context) {
  // const user = await getSessionFromContext(context);
  // if (!user) {
    // redirectTo(context, '/auth/signin');
  // }

  // let param = {};
  // param['limit'] = 3;
  // const products = await getProducts(param);
  /*.then(res => { 
      console.log(res.data);
      return res.data;
    });*/
    
  const products = await getProducts();
  let name = products.data.data.map(prod => {
    let t={value: prod.id, label: prod.name};
    return t;
  })

  let prods = products.data.data.slice(0, 4);
  // console.log(products.data.data);
  // console.log(name);

  // console.log(name.splice(4));

  return {
    props: {
      // user,
      // products: sampleData.data,
      products: prods,
      name: name
    }
  };
}

export default function Home(props) {

  const [products, setProducts] = useState(props.products);
  const [name, setName] = useState(props.name);
  const [selectId, setSelectId] = useState(-1);

  const handleChange = (selectedOption) => {
    console.log(`Option selected:`, selectedOption);
    if(selectedOption) {
      setSelectId(selectedOption.value);
    } else {
      setSelectId(-1);
    }
  };

  const handleSearch = () => {
    if(selectId>0)
      Router.push(`/product/${selectId}`);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Ngo xanh</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <a className='contact-link view-all' onClick={()=>{Router.push('/contact');}}>Liên hệ</a>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to ngoxanh
        </h1>

        <div className='search-box'>
          <div className='search-input-container'>
            {/* <input
                className='search-input'
                type='text'
                id='header-search'
                placeholder='Tim san pham'
                name='s' 
            />           */}
            <Select 
              className='search-input'
              options={name} placeholder='Tên sản phẩm...' 
              isClearable={true} 
              isSearchable={true} 
              onChange={handleChange} 
              instanceId='select prod'
              />
          </div>
          <div className='search-btn-container'>
            <button className='search-btn' onClick={handleSearch}>Tìm</button>
          </div>
        </div>
      </main>
      <TopProduct
        products={products}
      />
      <footer className={styles.footer}>
        <PageFooter />
        <div style={{minHeight:'10vh'}}></div>
      </footer>
    </div>
  )
}
