import { useEffect, useState, useRef } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import { getSessionFromContext } from '../services/auth';
import Router from 'next/router';

import { getProducts } from '../services/product';

import styles from '../styles/Home.module.css'

import TopProduct from '../components/top-product/top-product';
import PageFooter from '../components/footer/footer';
import sampleData from '../public/getProducts.json'

export async function getServerSideProps(context) {
  // const user = await getSessionFromContext(context);
  // if (!user) {
    // redirectTo(context, '/auth/signin');
  // }

  let param = {};
  param['limit'] = 3;
  const products = await getProducts(param);
  /*.then(res => { 
      console.log(res.data);
      return res.data;
    });*/
    
  console.log(products.data.data);

  return {
    props: {
      // user,
      // products: sampleData.data,
      products: products.data.data,
    }
  };
}

export default function Home(props) {

  const [products, setProducts] = useState(props.products);

  return (
    <div className={styles.container}>
      <Head>
        <title>Ngo xanh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <a className='contact-link view-all' onClick={()=>{Router.push('/contact');}}>Liên hệ</a>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to ngoxanh
        </h1>

        <div className="search-box">
          <div className="search-input-container">
            <input
                className="search-input"
                type="text"
                id="header-search"
                placeholder="Tim san pham"
                name="s" 
            />          
          </div>
          <div className="search-btn-container">
            <button className="search-btn">Tim</button>
          </div>
        </div>
      </main>
      <TopProduct
        products={products}
      />
      <footer className={styles.footer}>
        <PageFooter />
        <div style={{minHeight:'10vh'}}></div>
      </footer>
    </div>
  )
}
